/* Copied/reformatted from https://xkcd.com/color/rgb.txt,
the 'XKCD color survey.'  Discussion of the survey is at
https://blog.xkcd.com/2010/05/03/color-survey-results/.  The
colors are shown at https://xkcd.com/color/rgb/ .

# License: http://creativecommons.org/publicdomain/zero/1.0/

   Code snippet used to convert 'rgb.txt' to the following
#defines is...

#include <stdio.h>
#include <string.h>
#include <assert.h>

int main( const int argc, const char **argv)
{
   char buff[200];
   FILE *ifile = fopen( "rgb.txt", "rb");

   while( fgets( buff, sizeof( buff), ifile))
      if( *buff != '#')
         {
         char *color_loc = strchr( buff + 1, '#');
         int i;

         assert( color_loc);
         assert( color_loc[-1] == 9);
         assert( color_loc < buff + 28);
         color_loc[-1] = '\0';
         color_loc++;
         for( i = 0; buff[i]; i++)
            if( buff[i] == ' ')
               buff[i] = '_';
            else if( buff[i] >= 'a' && buff[i] <= 'z')
               buff[i] -= 'a' - 'A';
            else if( buff[i] == '/')
               buff[i] = 's';
            else if( buff[i] == '\'')
               buff[i] = 'a';
            else
               assert( 1);
         printf( "#define RGB_%-28s0x%s", buff, color_loc);
         }
   return( 0);
}
*/

#define RGB_CLOUDY_BLUE                 0xacc2d9
#define RGB_DARK_PASTEL_GREEN           0x56ae57
#define RGB_DUST                        0xb2996e
#define RGB_ELECTRIC_LIME               0xa8ff04
#define RGB_FRESH_GREEN                 0x69d84f
#define RGB_LIGHT_EGGPLANT              0x894585
#define RGB_NASTY_GREEN                 0x70b23f
#define RGB_REALLY_LIGHT_BLUE           0xd4ffff
#define RGB_TEA                         0x65ab7c
#define RGB_WARM_PURPLE                 0x952e8f
#define RGB_YELLOWISH_TAN               0xfcfc81
#define RGB_CEMENT                      0xa5a391
#define RGB_DARK_GRASS_GREEN            0x388004
#define RGB_DUSTY_TEAL                  0x4c9085
#define RGB_GREY_TEAL                   0x5e9b8a
#define RGB_MACARONI_AND_CHEESE         0xefb435
#define RGB_PINKISH_TAN                 0xd99b82
#define RGB_SPRUCE                      0x0a5f38
#define RGB_STRONG_BLUE                 0x0c06f7
#define RGB_TOXIC_GREEN                 0x61de2a
#define RGB_WINDOWS_BLUE                0x3778bf
#define RGB_BLUE_BLUE                   0x2242c7
#define RGB_BLUE_WITH_A_HINT_OF_PURPLE  0x533cc6
#define RGB_BOOGER                      0x9bb53c
#define RGB_BRIGHT_SEA_GREEN            0x05ffa6
#define RGB_DARK_GREEN_BLUE             0x1f6357
#define RGB_DEEP_TURQUOISE              0x017374
#define RGB_GREEN_TEAL                  0x0cb577
#define RGB_STRONG_PINK                 0xff0789
#define RGB_BLAND                       0xafa88b
#define RGB_DEEP_AQUA                   0x08787f
#define RGB_LAVENDER_PINK               0xdd85d7
#define RGB_LIGHT_MOSS_GREEN            0xa6c875
#define RGB_LIGHT_SEAFOAM_GREEN         0xa7ffb5
#define RGB_OLIVE_YELLOW                0xc2b709
#define RGB_PIG_PINK                    0xe78ea5
#define RGB_DEEP_LILAC                  0x966ebd
#define RGB_DESERT                      0xccad60
#define RGB_DUSTY_LAVENDER              0xac86a8
#define RGB_PURPLEY_GREY                0x947e94
#define RGB_PURPLY                      0x983fb2
#define RGB_CANDY_PINK                  0xff63e9
#define RGB_LIGHT_PASTEL_GREEN          0xb2fba5
#define RGB_BORING_GREEN                0x63b365
#define RGB_KIWI_GREEN                  0x8ee53f
#define RGB_LIGHT_GREY_GREEN            0xb7e1a1
#define RGB_ORANGE_PINK                 0xff6f52
#define RGB_TEA_GREEN                   0xbdf8a3
#define RGB_VERY_LIGHT_BROWN            0xd3b683
#define RGB_EGG_SHELL                   0xfffcc4
#define RGB_EGGPLANT_PURPLE             0x430541
#define RGB_POWDER_PINK                 0xffb2d0
#define RGB_REDDISH_GREY                0x997570
#define RGB_BABY_SHIT_BROWN             0xad900d
#define RGB_LILIAC                      0xc48efd
#define RGB_STORMY_BLUE                 0x507b9c
#define RGB_UGLY_BROWN                  0x7d7103
#define RGB_CUSTARD                     0xfffd78
#define RGB_DARKISH_PINK                0xda467d
#define RGB_DEEP_BROWN                  0x410200
#define RGB_GREENISH_BEIGE              0xc9d179
#define RGB_MANILLA                     0xfffa86
#define RGB_OFF_BLUE                    0x5684ae
#define RGB_BATTLESHIP_GREY             0x6b7c85
#define RGB_BROWNY_GREEN                0x6f6c0a
#define RGB_BRUISE                      0x7e4071
#define RGB_KELLEY_GREEN                0x009337
#define RGB_SICKLY_YELLOW               0xd0e429
#define RGB_SUNNY_YELLOW                0xfff917
#define RGB_AZUL                        0x1d5dec
#define RGB_DARKGREEN                   0x054907
#define RGB_GREENsYELLOW                0xb5ce08
#define RGB_LICHEN                      0x8fb67b
#define RGB_LIGHT_LIGHT_GREEN           0xc8ffb0
#define RGB_PALE_GOLD                   0xfdde6c
#define RGB_SUN_YELLOW                  0xffdf22
#define RGB_TAN_GREEN                   0xa9be70
#define RGB_BURPLE                      0x6832e3
#define RGB_BUTTERSCOTCH                0xfdb147
#define RGB_TOUPE                       0xc7ac7d
#define RGB_DARK_CREAM                  0xfff39a
#define RGB_INDIAN_RED                  0x850e04
#define RGB_LIGHT_LAVENDAR              0xefc0fe
#define RGB_POISON_GREEN                0x40fd14
#define RGB_BABY_PUKE_GREEN             0xb6c406
#define RGB_BRIGHT_YELLOW_GREEN         0x9dff00
#define RGB_CHARCOAL_GREY               0x3c4142
#define RGB_SQUASH                      0xf2ab15
#define RGB_CINNAMON                    0xac4f06
#define RGB_LIGHT_PEA_GREEN             0xc4fe82
#define RGB_RADIOACTIVE_GREEN           0x2cfa1f
#define RGB_RAW_SIENNA                  0x9a6200
#define RGB_BABY_PURPLE                 0xca9bf7
#define RGB_COCOA                       0x875f42
#define RGB_LIGHT_ROYAL_BLUE            0x3a2efe
#define RGB_ORANGEISH                   0xfd8d49
#define RGB_RUST_BROWN                  0x8b3103
#define RGB_SAND_BROWN                  0xcba560
#define RGB_SWAMP                       0x698339
#define RGB_TEALISH_GREEN               0x0cdc73
#define RGB_BURNT_SIENA                 0xb75203
#define RGB_CAMO                        0x7f8f4e
#define RGB_DUSK_BLUE                   0x26538d
#define RGB_FERN                        0x63a950
#define RGB_OLD_ROSE                    0xc87f89
#define RGB_PALE_LIGHT_GREEN            0xb1fc99
#define RGB_PEACHY_PINK                 0xff9a8a
#define RGB_ROSY_PINK                   0xf6688e
#define RGB_LIGHT_BLUISH_GREEN          0x76fda8
#define RGB_LIGHT_BRIGHT_GREEN          0x53fe5c
#define RGB_LIGHT_NEON_GREEN            0x4efd54
#define RGB_LIGHT_SEAFOAM               0xa0febf
#define RGB_TIFFANY_BLUE                0x7bf2da
#define RGB_WASHED_OUT_GREEN            0xbcf5a6
#define RGB_BROWNY_ORANGE               0xca6b02
#define RGB_NICE_BLUE                   0x107ab0
#define RGB_SAPPHIRE                    0x2138ab
#define RGB_GREYISH_TEAL                0x719f91
#define RGB_ORANGEY_YELLOW              0xfdb915
#define RGB_PARCHMENT                   0xfefcaf
#define RGB_STRAW                       0xfcf679
#define RGB_VERY_DARK_BROWN             0x1d0200
#define RGB_TERRACOTA                   0xcb6843
#define RGB_UGLY_BLUE                   0x31668a
#define RGB_CLEAR_BLUE                  0x247afd
#define RGB_CREME                       0xffffb6
#define RGB_FOAM_GREEN                  0x90fda9
#define RGB_GREYsGREEN                  0x86a17d
#define RGB_LIGHT_GOLD                  0xfddc5c
#define RGB_SEAFOAM_BLUE                0x78d1b6
#define RGB_TOPAZ                       0x13bbaf
#define RGB_VIOLET_PINK                 0xfb5ffc
#define RGB_WINTERGREEN                 0x20f986
#define RGB_YELLOW_TAN                  0xffe36e
#define RGB_DARK_FUCHSIA                0x9d0759
#define RGB_INDIGO_BLUE                 0x3a18b1
#define RGB_LIGHT_YELLOWISH_GREEN       0xc2ff89
#define RGB_PALE_MAGENTA                0xd767ad
#define RGB_RICH_PURPLE                 0x720058
#define RGB_SUNFLOWER_YELLOW            0xffda03
#define RGB_GREENsBLUE                  0x01c08d
#define RGB_LEATHER                     0xac7434
#define RGB_RACING_GREEN                0x014600
#define RGB_VIVID_PURPLE                0x9900fa
#define RGB_DARK_ROYAL_BLUE             0x02066f
#define RGB_HAZEL                       0x8e7618
#define RGB_MUTED_PINK                  0xd1768f
#define RGB_BOOGER_GREEN                0x96b403
#define RGB_CANARY                      0xfdff63
#define RGB_COOL_GREY                   0x95a3a6
#define RGB_DARK_TAUPE                  0x7f684e
#define RGB_DARKISH_PURPLE              0x751973
#define RGB_TRUE_GREEN                  0x089404
#define RGB_CORAL_PINK                  0xff6163
#define RGB_DARK_SAGE                   0x598556
#define RGB_DARK_SLATE_BLUE             0x214761
#define RGB_FLAT_BLUE                   0x3c73a8
#define RGB_MUSHROOM                    0xba9e88
#define RGB_RICH_BLUE                   0x021bf9
#define RGB_DIRTY_PURPLE                0x734a65
#define RGB_GREENBLUE                   0x23c48b
#define RGB_ICKY_GREEN                  0x8fae22
#define RGB_LIGHT_KHAKI                 0xe6f2a2
#define RGB_WARM_BLUE                   0x4b57db
#define RGB_DARK_HOT_PINK               0xd90166
#define RGB_DEEP_SEA_BLUE               0x015482
#define RGB_CARMINE                     0x9d0216
#define RGB_DARK_YELLOW_GREEN           0x728f02
#define RGB_PALE_PEACH                  0xffe5ad
#define RGB_PLUM_PURPLE                 0x4e0550
#define RGB_GOLDEN_ROD                  0xf9bc08
#define RGB_NEON_RED                    0xff073a
#define RGB_OLD_PINK                    0xc77986
#define RGB_VERY_PALE_BLUE              0xd6fffe
#define RGB_BLOOD_ORANGE                0xfe4b03
#define RGB_GRAPEFRUIT                  0xfd5956
#define RGB_SAND_YELLOW                 0xfce166
#define RGB_CLAY_BROWN                  0xb2713d
#define RGB_DARK_BLUE_GREY              0x1f3b4d
#define RGB_FLAT_GREEN                  0x699d4c
#define RGB_LIGHT_GREEN_BLUE            0x56fca2
#define RGB_WARM_PINK                   0xfb5581
#define RGB_DODGER_BLUE                 0x3e82fc
#define RGB_GROSS_GREEN                 0xa0bf16
#define RGB_ICE                         0xd6fffa
#define RGB_METALLIC_BLUE               0x4f738e
#define RGB_PALE_SALMON                 0xffb19a
#define RGB_SAP_GREEN                   0x5c8b15
#define RGB_ALGAE                       0x54ac68
#define RGB_BLUEY_GREY                  0x89a0b0
#define RGB_GREENY_GREY                 0x7ea07a
#define RGB_HIGHLIGHTER_GREEN           0x1bfc06
#define RGB_LIGHT_LIGHT_BLUE            0xcafffb
#define RGB_LIGHT_MINT                  0xb6ffbb
#define RGB_RAW_UMBER                   0xa75e09
#define RGB_VIVID_BLUE                  0x152eff
#define RGB_DEEP_LAVENDER               0x8d5eb7
#define RGB_DULL_TEAL                   0x5f9e8f
#define RGB_LIGHT_GREENISH_BLUE         0x63f7b4
#define RGB_MUD_GREEN                   0x606602
#define RGB_PINKY                       0xfc86aa
#define RGB_RED_WINE                    0x8c0034
#define RGB_SHIT_GREEN                  0x758000
#define RGB_TAN_BROWN                   0xab7e4c
#define RGB_DARKBLUE                    0x030764
#define RGB_ROSA                        0xfe86a4
#define RGB_LIPSTICK                    0xd5174e
#define RGB_PALE_MAUVE                  0xfed0fc
#define RGB_CLARET                      0x680018
#define RGB_DANDELION                   0xfedf08
#define RGB_ORANGERED                   0xfe420f
#define RGB_POOP_GREEN                  0x6f7c00
#define RGB_RUBY                        0xca0147
#define RGB_DARK                        0x1b2431
#define RGB_GREENISH_TURQUOISE          0x00fbb0
#define RGB_PASTEL_RED                  0xdb5856
#define RGB_PISS_YELLOW                 0xddd618
#define RGB_BRIGHT_CYAN                 0x41fdfe
#define RGB_DARK_CORAL                  0xcf524e
#define RGB_ALGAE_GREEN                 0x21c36f
#define RGB_DARKISH_RED                 0xa90308
#define RGB_REDDY_BROWN                 0x6e1005
#define RGB_BLUSH_PINK                  0xfe828c
#define RGB_CAMOUFLAGE_GREEN            0x4b6113
#define RGB_LAWN_GREEN                  0x4da409
#define RGB_PUTTY                       0xbeae8a
#define RGB_VIBRANT_BLUE                0x0339f8
#define RGB_DARK_SAND                   0xa88f59
#define RGB_PURPLEsBLUE                 0x5d21d0
#define RGB_SAFFRON                     0xfeb209
#define RGB_TWILIGHT                    0x4e518b
#define RGB_WARM_BROWN                  0x964e02
#define RGB_BLUEGREY                    0x85a3b2
#define RGB_BUBBLE_GUM_PINK             0xff69af
#define RGB_DUCK_EGG_BLUE               0xc3fbf4
#define RGB_GREENISH_CYAN               0x2afeb7
#define RGB_PETROL                      0x005f6a
#define RGB_ROYAL                       0x0c1793
#define RGB_BUTTER                      0xffff81
#define RGB_DUSTY_ORANGE                0xf0833a
#define RGB_OFF_YELLOW                  0xf1f33f
#define RGB_PALE_OLIVE_GREEN            0xb1d27b
#define RGB_ORANGISH                    0xfc824a
#define RGB_LEAF                        0x71aa34
#define RGB_LIGHT_BLUE_GREY             0xb7c9e2
#define RGB_DRIED_BLOOD                 0x4b0101
#define RGB_LIGHTISH_PURPLE             0xa552e6
#define RGB_RUSTY_RED                   0xaf2f0d
#define RGB_LAVENDER_BLUE               0x8b88f8
#define RGB_LIGHT_GRASS_GREEN           0x9af764
#define RGB_LIGHT_MINT_GREEN            0xa6fbb2
#define RGB_SUNFLOWER                   0xffc512
#define RGB_VELVET                      0x750851
#define RGB_BRICK_ORANGE                0xc14a09
#define RGB_LIGHTISH_RED                0xfe2f4a
#define RGB_PURE_BLUE                   0x0203e2
#define RGB_TWILIGHT_BLUE               0x0a437a
#define RGB_VIOLET_RED                  0xa50055
#define RGB_YELLOWY_BROWN               0xae8b0c
#define RGB_CARNATION                   0xfd798f
#define RGB_MUDDY_YELLOW                0xbfac05
#define RGB_DARK_SEAFOAM_GREEN          0x3eaf76
#define RGB_DEEP_ROSE                   0xc74767
#define RGB_DUSTY_RED                   0xb9484e
#define RGB_GREYsBLUE                   0x647d8e
#define RGB_LEMON_LIME                  0xbffe28
#define RGB_PURPLEsPINK                 0xd725de
#define RGB_BROWN_YELLOW                0xb29705
#define RGB_PURPLE_BROWN                0x673a3f
#define RGB_WISTERIA                    0xa87dc2
#define RGB_BANANA_YELLOW               0xfafe4b
#define RGB_LIPSTICK_RED                0xc0022f
#define RGB_WATER_BLUE                  0x0e87cc
#define RGB_BROWN_GREY                  0x8d8468
#define RGB_VIBRANT_PURPLE              0xad03de
#define RGB_BABY_GREEN                  0x8cff9e
#define RGB_BARF_GREEN                  0x94ac02
#define RGB_EGGSHELL_BLUE               0xc4fff7
#define RGB_SANDY_YELLOW                0xfdee73
#define RGB_COOL_GREEN                  0x33b864
#define RGB_PALE                        0xfff9d0
#define RGB_BLUEsGREY                   0x758da3
#define RGB_HOT_MAGENTA                 0xf504c9
#define RGB_GREYBLUE                    0x77a1b5
#define RGB_PURPLEY                     0x8756e4
#define RGB_BABY_SHIT_GREEN             0x889717
#define RGB_BROWNISH_PINK               0xc27e79
#define RGB_DARK_AQUAMARINE             0x017371
#define RGB_DIARRHEA                    0x9f8303
#define RGB_LIGHT_MUSTARD               0xf7d560
#define RGB_PALE_SKY_BLUE               0xbdf6fe
#define RGB_TURTLE_GREEN                0x75b84f
#define RGB_BRIGHT_OLIVE                0x9cbb04
#define RGB_DARK_GREY_BLUE              0x29465b
#define RGB_GREENY_BROWN                0x696006
#define RGB_LEMON_GREEN                 0xadf802
#define RGB_LIGHT_PERIWINKLE            0xc1c6fc
#define RGB_SEAWEED_GREEN               0x35ad6b
#define RGB_SUNSHINE_YELLOW             0xfffd37
#define RGB_UGLY_PURPLE                 0xa442a0
#define RGB_MEDIUM_PINK                 0xf36196
#define RGB_PUKE_BROWN                  0x947706
#define RGB_VERY_LIGHT_PINK             0xfff4f2
#define RGB_VIRIDIAN                    0x1e9167
#define RGB_BILE                        0xb5c306
#define RGB_FADED_YELLOW                0xfeff7f
#define RGB_VERY_PALE_GREEN             0xcffdbc
#define RGB_VIBRANT_GREEN               0x0add08
#define RGB_BRIGHT_LIME                 0x87fd05
#define RGB_SPEARMINT                   0x1ef876
#define RGB_LIGHT_AQUAMARINE            0x7bfdc7
#define RGB_LIGHT_SAGE                  0xbcecac
#define RGB_YELLOWGREEN                 0xbbf90f
#define RGB_BABY_POO                    0xab9004
#define RGB_DARK_SEAFOAM                0x1fb57a
#define RGB_DEEP_TEAL                   0x00555a
#define RGB_HEATHER                     0xa484ac
#define RGB_RUST_ORANGE                 0xc45508
#define RGB_DIRTY_BLUE                  0x3f829d
#define RGB_FERN_GREEN                  0x548d44
#define RGB_BRIGHT_LILAC                0xc95efb
#define RGB_WEIRD_GREEN                 0x3ae57f
#define RGB_PEACOCK_BLUE                0x016795
#define RGB_AVOCADO_GREEN               0x87a922
#define RGB_FADED_ORANGE                0xf0944d
#define RGB_GRAPE_PURPLE                0x5d1451
#define RGB_HOT_GREEN                   0x25ff29
#define RGB_LIME_YELLOW                 0xd0fe1d
#define RGB_MANGO                       0xffa62b
#define RGB_SHAMROCK                    0x01b44c
#define RGB_BUBBLEGUM                   0xff6cb5
#define RGB_PURPLISH_BROWN              0x6b4247
#define RGB_VOMIT_YELLOW                0xc7c10c
#define RGB_PALE_CYAN                   0xb7fffa
#define RGB_KEY_LIME                    0xaeff6e
#define RGB_TOMATO_RED                  0xec2d01
#define RGB_LIGHTGREEN                  0x76ff7b
#define RGB_MERLOT                      0x730039
#define RGB_NIGHT_BLUE                  0x040348
#define RGB_PURPLEISH_PINK              0xdf4ec8
#define RGB_APPLE                       0x6ecb3c
#define RGB_BABY_POOP_GREEN             0x8f9805
#define RGB_GREEN_APPLE                 0x5edc1f
#define RGB_HELIOTROPE                  0xd94ff5
#define RGB_YELLOWsGREEN                0xc8fd3d
#define RGB_ALMOST_BLACK                0x070d0d
#define RGB_COOL_BLUE                   0x4984b8
#define RGB_LEAFY_GREEN                 0x51b73b
#define RGB_MUSTARD_BROWN               0xac7e04
#define RGB_DUSK                        0x4e5481
#define RGB_DULL_BROWN                  0x876e4b
#define RGB_FROG_GREEN                  0x58bc08
#define RGB_VIVID_GREEN                 0x2fef10
#define RGB_BRIGHT_LIGHT_GREEN          0x2dfe54
#define RGB_FLURO_GREEN                 0x0aff02
#define RGB_KIWI                        0x9cef43
#define RGB_SEAWEED                     0x18d17b
#define RGB_NAVY_GREEN                  0x35530a
#define RGB_ULTRAMARINE_BLUE            0x1805db
#define RGB_IRIS                        0x6258c4
#define RGB_PASTEL_ORANGE               0xff964f
#define RGB_YELLOWISH_ORANGE            0xffab0f
#define RGB_PERRYWINKLE                 0x8f8ce7
#define RGB_TEALISH                     0x24bca8
#define RGB_DARK_PLUM                   0x3f012c
#define RGB_PEAR                        0xcbf85f
#define RGB_PINKISH_ORANGE              0xff724c
#define RGB_MIDNIGHT_PURPLE             0x280137
#define RGB_LIGHT_URPLE                 0xb36ff6
#define RGB_DARK_MINT                   0x48c072
#define RGB_GREENISH_TAN                0xbccb7a
#define RGB_LIGHT_BURGUNDY              0xa8415b
#define RGB_TURQUOISE_BLUE              0x06b1c4
#define RGB_UGLY_PINK                   0xcd7584
#define RGB_SANDY                       0xf1da7a
#define RGB_ELECTRIC_PINK               0xff0490
#define RGB_MUTED_PURPLE                0x805b87
#define RGB_MID_GREEN                   0x50a747
#define RGB_GREYISH                     0xa8a495
#define RGB_NEON_YELLOW                 0xcfff04
#define RGB_BANANA                      0xffff7e
#define RGB_CARNATION_PINK              0xff7fa7
#define RGB_TOMATO                      0xef4026
#define RGB_SEA                         0x3c9992
#define RGB_MUDDY_BROWN                 0x886806
#define RGB_TURQUOISE_GREEN             0x04f489
#define RGB_BUFF                        0xfef69e
#define RGB_FAWN                        0xcfaf7b
#define RGB_MUTED_BLUE                  0x3b719f
#define RGB_PALE_ROSE                   0xfdc1c5
#define RGB_DARK_MINT_GREEN             0x20c073
#define RGB_AMETHYST                    0x9b5fc0
#define RGB_BLUEsGREEN                  0x0f9b8e
#define RGB_CHESTNUT                    0x742802
#define RGB_SICK_GREEN                  0x9db92c
#define RGB_PEA                         0xa4bf20
#define RGB_RUSTY_ORANGE                0xcd5909
#define RGB_STONE                       0xada587
#define RGB_ROSE_RED                    0xbe013c
#define RGB_PALE_AQUA                   0xb8ffeb
#define RGB_DEEP_ORANGE                 0xdc4d01
#define RGB_EARTH                       0xa2653e
#define RGB_MOSSY_GREEN                 0x638b27
#define RGB_GRASSY_GREEN                0x419c03
#define RGB_PALE_LIME_GREEN             0xb1ff65
#define RGB_LIGHT_GREY_BLUE             0x9dbcd4
#define RGB_PALE_GREY                   0xfdfdfe
#define RGB_ASPARAGUS                   0x77ab56
#define RGB_BLUEBERRY                   0x464196
#define RGB_PURPLE_RED                  0x990147
#define RGB_PALE_LIME                   0xbefd73
#define RGB_GREENISH_TEAL               0x32bf84
#define RGB_CARAMEL                     0xaf6f09
#define RGB_DEEP_MAGENTA                0xa0025c
#define RGB_LIGHT_PEACH                 0xffd8b1
#define RGB_MILK_CHOCOLATE              0x7f4e1e
#define RGB_OCHER                       0xbf9b0c
#define RGB_OFF_GREEN                   0x6ba353
#define RGB_PURPLY_PINK                 0xf075e6
#define RGB_LIGHTBLUE                   0x7bc8f6
#define RGB_DUSKY_BLUE                  0x475f94
#define RGB_GOLDEN                      0xf5bf03
#define RGB_LIGHT_BEIGE                 0xfffeb6
#define RGB_BUTTER_YELLOW               0xfffd74
#define RGB_DUSKY_PURPLE                0x895b7b
#define RGB_FRENCH_BLUE                 0x436bad
#define RGB_UGLY_YELLOW                 0xd0c101
#define RGB_GREENY_YELLOW               0xc6f808
#define RGB_ORANGISH_RED                0xf43605
#define RGB_SHAMROCK_GREEN              0x02c14d
#define RGB_ORANGISH_BROWN              0xb25f03
#define RGB_TREE_GREEN                  0x2a7e19
#define RGB_DEEP_VIOLET                 0x490648
#define RGB_GUNMETAL                    0x536267
#define RGB_BLUEsPURPLE                 0x5a06ef
#define RGB_CHERRY                      0xcf0234
#define RGB_SANDY_BROWN                 0xc4a661
#define RGB_WARM_GREY                   0x978a84
#define RGB_DARK_INDIGO                 0x1f0954
#define RGB_MIDNIGHT                    0x03012d
#define RGB_BLUEY_GREEN                 0x2bb179
#define RGB_GREY_PINK                   0xc3909b
#define RGB_SOFT_PURPLE                 0xa66fb5
#define RGB_BLOOD                       0x770001
#define RGB_BROWN_RED                   0x922b05
#define RGB_MEDIUM_GREY                 0x7d7f7c
#define RGB_BERRY                       0x990f4b
#define RGB_POO                         0x8f7303
#define RGB_PURPLEY_PINK                0xc83cb9
#define RGB_LIGHT_SALMON                0xfea993
#define RGB_SNOT                        0xacbb0d
#define RGB_EASTER_PURPLE               0xc071fe
#define RGB_LIGHT_YELLOW_GREEN          0xccfd7f
#define RGB_DARK_NAVY_BLUE              0x00022e
#define RGB_DRAB                        0x828344
#define RGB_LIGHT_ROSE                  0xffc5cb
#define RGB_ROUGE                       0xab1239
#define RGB_PURPLISH_RED                0xb0054b
#define RGB_SLIME_GREEN                 0x99cc04
#define RGB_BABY_POOP                   0x937c00
#define RGB_IRISH_GREEN                 0x019529
#define RGB_PINKsPURPLE                 0xef1de7
#define RGB_DARK_NAVY                   0x000435
#define RGB_GREENY_BLUE                 0x42b395
#define RGB_LIGHT_PLUM                  0x9d5783
#define RGB_PINKISH_GREY                0xc8aca9
#define RGB_DIRTY_ORANGE                0xc87606
#define RGB_RUST_RED                    0xaa2704
#define RGB_PALE_LILAC                  0xe4cbff
#define RGB_ORANGEY_RED                 0xfa4224
#define RGB_PRIMARY_BLUE                0x0804f9
#define RGB_KERMIT_GREEN                0x5cb200
#define RGB_BROWNISH_PURPLE             0x76424e
#define RGB_MURKY_GREEN                 0x6c7a0e
#define RGB_WHEAT                       0xfbdd7e
#define RGB_VERY_DARK_PURPLE            0x2a0134
#define RGB_BOTTLE_GREEN                0x044a05
#define RGB_WATERMELON                  0xfd4659
#define RGB_DEEP_SKY_BLUE               0x0d75f8
#define RGB_FIRE_ENGINE_RED             0xfe0002
#define RGB_YELLOW_OCHRE                0xcb9d06
#define RGB_PUMPKIN_ORANGE              0xfb7d07
#define RGB_PALE_OLIVE                  0xb9cc81
#define RGB_LIGHT_LILAC                 0xedc8ff
#define RGB_LIGHTISH_GREEN              0x61e160
#define RGB_CAROLINA_BLUE               0x8ab8fe
#define RGB_MULBERRY                    0x920a4e
#define RGB_SHOCKING_PINK               0xfe02a2
#define RGB_AUBURN                      0x9a3001
#define RGB_BRIGHT_LIME_GREEN           0x65fe08
#define RGB_CELADON                     0xbefdb7
#define RGB_PINKISH_BROWN               0xb17261
#define RGB_POO_BROWN                   0x885f01
#define RGB_BRIGHT_SKY_BLUE             0x02ccfe
#define RGB_CELERY                      0xc1fd95
#define RGB_DIRT_BROWN                  0x836539
#define RGB_STRAWBERRY                  0xfb2943
#define RGB_DARK_LIME                   0x84b701
#define RGB_COPPER                      0xb66325
#define RGB_MEDIUM_BROWN                0x7f5112
#define RGB_MUTED_GREEN                 0x5fa052
#define RGB_ROBINaS_EGG                 0x6dedfd
#define RGB_BRIGHT_AQUA                 0x0bf9ea
#define RGB_BRIGHT_LAVENDER             0xc760ff
#define RGB_IVORY                       0xffffcb
#define RGB_VERY_LIGHT_PURPLE           0xf6cefc
#define RGB_LIGHT_NAVY                  0x155084
#define RGB_PINK_RED                    0xf5054f
#define RGB_OLIVE_BROWN                 0x645403
#define RGB_POOP_BROWN                  0x7a5901
#define RGB_MUSTARD_GREEN               0xa8b504
#define RGB_OCEAN_GREEN                 0x3d9973
#define RGB_VERY_DARK_BLUE              0x000133
#define RGB_DUSTY_GREEN                 0x76a973
#define RGB_LIGHT_NAVY_BLUE             0x2e5a88
#define RGB_MINTY_GREEN                 0x0bf77d
#define RGB_ADOBE                       0xbd6c48
#define RGB_BARNEY                      0xac1db8
#define RGB_JADE_GREEN                  0x2baf6a
#define RGB_BRIGHT_LIGHT_BLUE           0x26f7fd
#define RGB_LIGHT_LIME                  0xaefd6c
#define RGB_DARK_KHAKI                  0x9b8f55
#define RGB_ORANGE_YELLOW               0xffad01
#define RGB_OCRE                        0xc69c04
#define RGB_MAIZE                       0xf4d054
#define RGB_FADED_PINK                  0xde9dac
#define RGB_BRITISH_RACING_GREEN        0x05480d
#define RGB_SANDSTONE                   0xc9ae74
#define RGB_MUD_BROWN                   0x60460f
#define RGB_LIGHT_SEA_GREEN             0x98f6b0
#define RGB_ROBIN_EGG_BLUE              0x8af1fe
#define RGB_AQUA_MARINE                 0x2ee8bb
#define RGB_DARK_SEA_GREEN              0x11875d
#define RGB_SOFT_PINK                   0xfdb0c0
#define RGB_ORANGEY_BROWN               0xb16002
#define RGB_CHERRY_RED                  0xf7022a
#define RGB_BURNT_YELLOW                0xd5ab09
#define RGB_BROWNISH_GREY               0x86775f
#define RGB_CAMEL                       0xc69f59
#define RGB_PURPLISH_GREY               0x7a687f
#define RGB_MARINE                      0x042e60
#define RGB_GREYISH_PINK                0xc88d94
#define RGB_PALE_TURQUOISE              0xa5fbd5
#define RGB_PASTEL_YELLOW               0xfffe71
#define RGB_BLUEY_PURPLE                0x6241c7
#define RGB_CANARY_YELLOW               0xfffe40
#define RGB_FADED_RED                   0xd3494e
#define RGB_SEPIA                       0x985e2b
#define RGB_COFFEE                      0xa6814c
#define RGB_BRIGHT_MAGENTA              0xff08e8
#define RGB_MOCHA                       0x9d7651
#define RGB_ECRU                        0xfeffca
#define RGB_PURPLEISH                   0x98568d
#define RGB_CRANBERRY                   0x9e003a
#define RGB_DARKISH_GREEN               0x287c37
#define RGB_BROWN_ORANGE                0xb96902
#define RGB_DUSKY_ROSE                  0xba6873
#define RGB_MELON                       0xff7855
#define RGB_SICKLY_GREEN                0x94b21c
#define RGB_SILVER                      0xc5c9c7
#define RGB_PURPLY_BLUE                 0x661aee
#define RGB_PURPLEISH_BLUE              0x6140ef
#define RGB_HOSPITAL_GREEN              0x9be5aa
#define RGB_SHIT_BROWN                  0x7b5804
#define RGB_MID_BLUE                    0x276ab3
#define RGB_AMBER                       0xfeb308
#define RGB_EASTER_GREEN                0x8cfd7e
#define RGB_SOFT_BLUE                   0x6488ea
#define RGB_CERULEAN_BLUE               0x056eee
#define RGB_GOLDEN_BROWN                0xb27a01
#define RGB_BRIGHT_TURQUOISE            0x0ffef9
#define RGB_RED_PINK                    0xfa2a55
#define RGB_RED_PURPLE                  0x820747
#define RGB_GREYISH_BROWN               0x7a6a4f
#define RGB_VERMILLION                  0xf4320c
#define RGB_RUSSET                      0xa13905
#define RGB_STEEL_GREY                  0x6f828a
#define RGB_LIGHTER_PURPLE              0xa55af4
#define RGB_BRIGHT_VIOLET               0xad0afd
#define RGB_PRUSSIAN_BLUE               0x004577
#define RGB_SLATE_GREEN                 0x658d6d
#define RGB_DIRTY_PINK                  0xca7b80
#define RGB_DARK_BLUE_GREEN             0x005249
#define RGB_PINE                        0x2b5d34
#define RGB_YELLOWY_GREEN               0xbff128
#define RGB_DARK_GOLD                   0xb59410
#define RGB_BLUISH                      0x2976bb
#define RGB_DARKISH_BLUE                0x014182
#define RGB_DULL_RED                    0xbb3f3f
#define RGB_PINKY_RED                   0xfc2647
#define RGB_BRONZE                      0xa87900
#define RGB_PALE_TEAL                   0x82cbb2
#define RGB_MILITARY_GREEN              0x667c3e
#define RGB_BARBIE_PINK                 0xfe46a5
#define RGB_BUBBLEGUM_PINK              0xfe83cc
#define RGB_PEA_SOUP_GREEN              0x94a617
#define RGB_DARK_MUSTARD                0xa88905
#define RGB_SHIT                        0x7f5f00
#define RGB_MEDIUM_PURPLE               0x9e43a2
#define RGB_VERY_DARK_GREEN             0x062e03
#define RGB_DIRT                        0x8a6e45
#define RGB_DUSKY_PINK                  0xcc7a8b
#define RGB_RED_VIOLET                  0x9e0168
#define RGB_LEMON_YELLOW                0xfdff38
#define RGB_PISTACHIO                   0xc0fa8b
#define RGB_DULL_YELLOW                 0xeedc5b
#define RGB_DARK_LIME_GREEN             0x7ebd01
#define RGB_DENIM_BLUE                  0x3b5b92
#define RGB_TEAL_BLUE                   0x01889f
#define RGB_LIGHTISH_BLUE               0x3d7afd
#define RGB_PURPLEY_BLUE                0x5f34e7
#define RGB_LIGHT_INDIGO                0x6d5acf
#define RGB_SWAMP_GREEN                 0x748500
#define RGB_BROWN_GREEN                 0x706c11
#define RGB_DARK_MAROON                 0x3c0008
#define RGB_HOT_PURPLE                  0xcb00f5
#define RGB_DARK_FOREST_GREEN           0x002d04
#define RGB_FADED_BLUE                  0x658cbb
#define RGB_DRAB_GREEN                  0x749551
#define RGB_LIGHT_LIME_GREEN            0xb9ff66
#define RGB_SNOT_GREEN                  0x9dc100
#define RGB_YELLOWISH                   0xfaee66
#define RGB_LIGHT_BLUE_GREEN            0x7efbb3
#define RGB_BORDEAUX                    0x7b002c
#define RGB_LIGHT_MAUVE                 0xc292a1
#define RGB_OCEAN                       0x017b92
#define RGB_MARIGOLD                    0xfcc006
#define RGB_MUDDY_GREEN                 0x657432
#define RGB_DULL_ORANGE                 0xd8863b
#define RGB_STEEL                       0x738595
#define RGB_ELECTRIC_PURPLE             0xaa23ff
#define RGB_FLUORESCENT_GREEN           0x08ff08
#define RGB_YELLOWISH_BROWN             0x9b7a01
#define RGB_BLUSH                       0xf29e8e
#define RGB_SOFT_GREEN                  0x6fc276
#define RGB_BRIGHT_ORANGE               0xff5b00
#define RGB_LEMON                       0xfdff52
#define RGB_PURPLE_GREY                 0x866f85
#define RGB_ACID_GREEN                  0x8ffe09
#define RGB_PALE_LAVENDER               0xeecffe
#define RGB_VIOLET_BLUE                 0x510ac9
#define RGB_LIGHT_FOREST_GREEN          0x4f9153
#define RGB_BURNT_RED                   0x9f2305
#define RGB_KHAKI_GREEN                 0x728639
#define RGB_CERISE                      0xde0c62
#define RGB_FADED_PURPLE                0x916e99
#define RGB_APRICOT                     0xffb16d
#define RGB_DARK_OLIVE_GREEN            0x3c4d03
#define RGB_GREY_BROWN                  0x7f7053
#define RGB_GREEN_GREY                  0x77926f
#define RGB_TRUE_BLUE                   0x010fcc
#define RGB_PALE_VIOLET                 0xceaefa
#define RGB_PERIWINKLE_BLUE             0x8f99fb
#define RGB_LIGHT_SKY_BLUE              0xc6fcff
#define RGB_BLURPLE                     0x5539cc
#define RGB_GREEN_BROWN                 0x544e03
#define RGB_BLUEGREEN                   0x017a79
#define RGB_BRIGHT_TEAL                 0x01f9c6
#define RGB_BROWNISH_YELLOW             0xc9b003
#define RGB_PEA_SOUP                    0x929901
#define RGB_FOREST                      0x0b5509
#define RGB_BARNEY_PURPLE               0xa00498
#define RGB_ULTRAMARINE                 0x2000b1
#define RGB_PURPLISH                    0x94568c
#define RGB_PUKE_YELLOW                 0xc2be0e
#define RGB_BLUISH_GREY                 0x748b97
#define RGB_DARK_PERIWINKLE             0x665fd1
#define RGB_DARK_LILAC                  0x9c6da5
#define RGB_REDDISH                     0xc44240
#define RGB_LIGHT_MAROON                0xa24857
#define RGB_DUSTY_PURPLE                0x825f87
#define RGB_TERRA_COTTA                 0xc9643b
#define RGB_AVOCADO                     0x90b134
#define RGB_MARINE_BLUE                 0x01386a
#define RGB_TEAL_GREEN                  0x25a36f
#define RGB_SLATE_GREY                  0x59656d
#define RGB_LIGHTER_GREEN               0x75fd63
#define RGB_ELECTRIC_GREEN              0x21fc0d
#define RGB_DUSTY_BLUE                  0x5a86ad
#define RGB_GOLDEN_YELLOW               0xfec615
#define RGB_BRIGHT_YELLOW               0xfffd01
#define RGB_LIGHT_LAVENDER              0xdfc5fe
#define RGB_UMBER                       0xb26400
#define RGB_POOP                        0x7f5e00
#define RGB_DARK_PEACH                  0xde7e5d
#define RGB_JUNGLE_GREEN                0x048243
#define RGB_EGGSHELL                    0xffffd4
#define RGB_DENIM                       0x3b638c
#define RGB_YELLOW_BROWN                0xb79400
#define RGB_DULL_PURPLE                 0x84597e
#define RGB_CHOCOLATE_BROWN             0x411900
#define RGB_WINE_RED                    0x7b0323
#define RGB_NEON_BLUE                   0x04d9ff
#define RGB_DIRTY_GREEN                 0x667e2c
#define RGB_LIGHT_TAN                   0xfbeeac
#define RGB_ICE_BLUE                    0xd7fffe
#define RGB_CADET_BLUE                  0x4e7496
#define RGB_DARK_MAUVE                  0x874c62
#define RGB_VERY_LIGHT_BLUE             0xd5ffff
#define RGB_GREY_PURPLE                 0x826d8c
#define RGB_PASTEL_PINK                 0xffbacd
#define RGB_VERY_LIGHT_GREEN            0xd1ffbd
#define RGB_DARK_SKY_BLUE               0x448ee4
#define RGB_EVERGREEN                   0x05472a
#define RGB_DULL_PINK                   0xd5869d
#define RGB_AUBERGINE                   0x3d0734
#define RGB_MAHOGANY                    0x4a0100
#define RGB_REDDISH_ORANGE              0xf8481c
#define RGB_DEEP_GREEN                  0x02590f
#define RGB_VOMIT_GREEN                 0x89a203
#define RGB_PURPLE_PINK                 0xe03fd8
#define RGB_DUSTY_PINK                  0xd58a94
#define RGB_FADED_GREEN                 0x7bb274
#define RGB_CAMO_GREEN                  0x526525
#define RGB_PINKY_PURPLE                0xc94cbe
#define RGB_PINK_PURPLE                 0xdb4bda
#define RGB_BROWNISH_RED                0x9e3623
#define RGB_DARK_ROSE                   0xb5485d
#define RGB_MUD                         0x735c12
#define RGB_BROWNISH                    0x9c6d57
#define RGB_EMERALD_GREEN               0x028f1e
#define RGB_PALE_BROWN                  0xb1916e
#define RGB_DULL_BLUE                   0x49759c
#define RGB_BURNT_UMBER                 0xa0450e
#define RGB_MEDIUM_GREEN                0x39ad48
#define RGB_CLAY                        0xb66a50
#define RGB_LIGHT_AQUA                  0x8cffdb
#define RGB_LIGHT_OLIVE_GREEN           0xa4be5c
#define RGB_BROWNISH_ORANGE             0xcb7723
#define RGB_DARK_AQUA                   0x05696b
#define RGB_PURPLISH_PINK               0xce5dae
#define RGB_DARK_SALMON                 0xc85a53
#define RGB_GREENISH_GREY               0x96ae8d
#define RGB_JADE                        0x1fa774
#define RGB_UGLY_GREEN                  0x7a9703
#define RGB_DARK_BEIGE                  0xac9362
#define RGB_EMERALD                     0x01a049
#define RGB_PALE_RED                    0xd9544d
#define RGB_LIGHT_MAGENTA               0xfa5ff7
#define RGB_SKY                         0x82cafc
#define RGB_LIGHT_CYAN                  0xacfffc
#define RGB_YELLOW_ORANGE               0xfcb001
#define RGB_REDDISH_PURPLE              0x910951
#define RGB_REDDISH_PINK                0xfe2c54
#define RGB_ORCHID                      0xc875c4
#define RGB_DIRTY_YELLOW                0xcdc50a
#define RGB_ORANGE_RED                  0xfd411e
#define RGB_DEEP_RED                    0x9a0200
#define RGB_ORANGE_BROWN                0xbe6400
#define RGB_COBALT_BLUE                 0x030aa7
#define RGB_NEON_PINK                   0xfe019a
#define RGB_ROSE_PINK                   0xf7879a
#define RGB_GREYISH_PURPLE              0x887191
#define RGB_RASPBERRY                   0xb00149
#define RGB_AQUA_GREEN                  0x12e193
#define RGB_SALMON_PINK                 0xfe7b7c
#define RGB_TANGERINE                   0xff9408
#define RGB_BROWNISH_GREEN              0x6a6e09
#define RGB_RED_BROWN                   0x8b2e16
#define RGB_GREENISH_BROWN              0x696112
#define RGB_PUMPKIN                     0xe17701
#define RGB_PINE_GREEN                  0x0a481e
#define RGB_CHARCOAL                    0x343837
#define RGB_BABY_PINK                   0xffb7ce
#define RGB_CORNFLOWER                  0x6a79f7
#define RGB_BLUE_VIOLET                 0x5d06e9
#define RGB_CHOCOLATE                   0x3d1c02
#define RGB_GREYISH_GREEN               0x82a67d
#define RGB_SCARLET                     0xbe0119
#define RGB_GREEN_YELLOW                0xc9ff27
#define RGB_DARK_OLIVE                  0x373e02
#define RGB_SIENNA                      0xa9561e
#define RGB_PASTEL_PURPLE               0xcaa0ff
#define RGB_TERRACOTTA                  0xca6641
#define RGB_AQUA_BLUE                   0x02d8e9
#define RGB_SAGE_GREEN                  0x88b378
#define RGB_BLOOD_RED                   0x980002
#define RGB_DEEP_PINK                   0xcb0162
#define RGB_GRASS                       0x5cac2d
#define RGB_MOSS                        0x769958
#define RGB_PASTEL_BLUE                 0xa2bffe
#define RGB_BLUISH_GREEN                0x10a674
#define RGB_GREEN_BLUE                  0x06b48b
#define RGB_DARK_TAN                    0xaf884a
#define RGB_GREENISH_BLUE               0x0b8b87
#define RGB_PALE_ORANGE                 0xffa756
#define RGB_VOMIT                       0xa2a415
#define RGB_FORREST_GREEN               0x154406
#define RGB_DARK_LAVENDER               0x856798
#define RGB_DARK_VIOLET                 0x34013f
#define RGB_PURPLE_BLUE                 0x632de9
#define RGB_DARK_CYAN                   0x0a888a
#define RGB_OLIVE_DRAB                  0x6f7632
#define RGB_PINKISH                     0xd46a7e
#define RGB_COBALT                      0x1e488f
#define RGB_NEON_PURPLE                 0xbc13fe
#define RGB_LIGHT_TURQUOISE             0x7ef4cc
#define RGB_APPLE_GREEN                 0x76cd26
#define RGB_DULL_GREEN                  0x74a662
#define RGB_WINE                        0x80013f
#define RGB_POWDER_BLUE                 0xb1d1fc
#define RGB_OFF_WHITE                   0xffffe4
#define RGB_ELECTRIC_BLUE               0x0652ff
#define RGB_DARK_TURQUOISE              0x045c5a
#define RGB_BLUE_PURPLE                 0x5729ce
#define RGB_AZURE                       0x069af3
#define RGB_BRIGHT_RED                  0xff000d
#define RGB_PINKISH_RED                 0xf10c45
#define RGB_CORNFLOWER_BLUE             0x5170d7
#define RGB_LIGHT_OLIVE                 0xacbf69
#define RGB_GRAPE                       0x6c3461
#define RGB_GREYISH_BLUE                0x5e819d
#define RGB_PURPLISH_BLUE               0x601ef9
#define RGB_YELLOWISH_GREEN             0xb0dd16
#define RGB_GREENISH_YELLOW             0xcdfd02
#define RGB_MEDIUM_BLUE                 0x2c6fbb
#define RGB_DUSTY_ROSE                  0xc0737a
#define RGB_LIGHT_VIOLET                0xd6b4fc
#define RGB_MIDNIGHT_BLUE               0x020035
#define RGB_BLUISH_PURPLE               0x703be7
#define RGB_RED_ORANGE                  0xfd3c06
#define RGB_DARK_MAGENTA                0x960056
#define RGB_GREENISH                    0x40a368
#define RGB_OCEAN_BLUE                  0x03719c
#define RGB_CORAL                       0xfc5a50
#define RGB_CREAM                       0xffffc2
#define RGB_REDDISH_BROWN               0x7f2b0a
#define RGB_BURNT_SIENNA                0xb04e0f
#define RGB_BRICK                       0xa03623
#define RGB_SAGE                        0x87ae73
#define RGB_GREY_GREEN                  0x789b73
#define RGB_WHITE                       0xffffff
#define RGB_ROBINaS_EGG_BLUE            0x98eff9
#define RGB_MOSS_GREEN                  0x658b38
#define RGB_STEEL_BLUE                  0x5a7d9a
#define RGB_EGGPLANT                    0x380835
#define RGB_LIGHT_YELLOW                0xfffe7a
#define RGB_LEAF_GREEN                  0x5ca904
#define RGB_LIGHT_GREY                  0xd8dcd6
#define RGB_PUKE                        0xa5a502
#define RGB_PINKISH_PURPLE              0xd648d7
#define RGB_SEA_BLUE                    0x047495
#define RGB_PALE_PURPLE                 0xb790d4
#define RGB_SLATE_BLUE                  0x5b7c99
#define RGB_BLUE_GREY                   0x607c8e
#define RGB_HUNTER_GREEN                0x0b4008
#define RGB_FUCHSIA                     0xed0dd9
#define RGB_CRIMSON                     0x8c000f
#define RGB_PALE_YELLOW                 0xffff84
#define RGB_OCHRE                       0xbf9005
#define RGB_MUSTARD_YELLOW              0xd2bd0a
#define RGB_LIGHT_RED                   0xff474c
#define RGB_CERULEAN                    0x0485d1
#define RGB_PALE_PINK                   0xffcfdc
#define RGB_DEEP_BLUE                   0x040273
#define RGB_RUST                        0xa83c09
#define RGB_LIGHT_TEAL                  0x90e4c1
#define RGB_SLATE                       0x516572
#define RGB_GOLDENROD                   0xfac205
#define RGB_DARK_YELLOW                 0xd5b60a
#define RGB_DARK_GREY                   0x363737
#define RGB_ARMY_GREEN                  0x4b5d16
#define RGB_GREY_BLUE                   0x6b8ba4
#define RGB_SEAFOAM                     0x80f9ad
#define RGB_PUCE                        0xa57e52
#define RGB_SPRING_GREEN                0xa9f971
#define RGB_DARK_ORANGE                 0xc65102
#define RGB_SAND                        0xe2ca76
#define RGB_PASTEL_GREEN                0xb0ff9d
#define RGB_MINT                        0x9ffeb0
#define RGB_LIGHT_ORANGE                0xfdaa48
#define RGB_BRIGHT_PINK                 0xfe01b1
#define RGB_CHARTREUSE                  0xc1f80a
#define RGB_DEEP_PURPLE                 0x36013f
#define RGB_DARK_BROWN                  0x341c02
#define RGB_TAUPE                       0xb9a281
#define RGB_PEA_GREEN                   0x8eab12
#define RGB_PUKE_GREEN                  0x9aae07
#define RGB_KELLY_GREEN                 0x02ab2e
#define RGB_SEAFOAM_GREEN               0x7af9ab
#define RGB_BLUE_GREEN                  0x137e6d
#define RGB_KHAKI                       0xaaa662
#define RGB_BURGUNDY                    0x610023
#define RGB_DARK_TEAL                   0x014d4e
#define RGB_BRICK_RED                   0x8f1402
#define RGB_ROYAL_PURPLE                0x4b006e
#define RGB_PLUM                        0x580f41
#define RGB_MINT_GREEN                  0x8fff9f
#define RGB_GOLD                        0xdbb40c
#define RGB_BABY_BLUE                   0xa2cffe
#define RGB_YELLOW_GREEN                0xc0fb2d
#define RGB_BRIGHT_PURPLE               0xbe03fd
#define RGB_DARK_RED                    0x840000
#define RGB_PALE_BLUE                   0xd0fefe
#define RGB_GRASS_GREEN                 0x3f9b0b
#define RGB_NAVY                        0x01153e
#define RGB_AQUAMARINE                  0x04d8b2
#define RGB_BURNT_ORANGE                0xc04e01
#define RGB_NEON_GREEN                  0x0cff0c
#define RGB_BRIGHT_BLUE                 0x0165fc
#define RGB_ROSE                        0xcf6275
#define RGB_LIGHT_PINK                  0xffd1df
#define RGB_MUSTARD                     0xceb301
#define RGB_INDIGO                      0x380282
#define RGB_LIME                        0xaaff32
#define RGB_SEA_GREEN                   0x53fca1
#define RGB_PERIWINKLE                  0x8e82fe
#define RGB_DARK_PINK                   0xcb416b
#define RGB_OLIVE_GREEN                 0x677a04
#define RGB_PEACH                       0xffb07c
#define RGB_PALE_GREEN                  0xc7fdb5
#define RGB_LIGHT_BROWN                 0xad8150
#define RGB_HOT_PINK                    0xff028d
#define RGB_BLACK                       0x000000
#define RGB_LILAC                       0xcea2fd
#define RGB_NAVY_BLUE                   0x001146
#define RGB_ROYAL_BLUE                  0x0504aa
#define RGB_BEIGE                       0xe6daa6
#define RGB_SALMON                      0xff796c
#define RGB_OLIVE                       0x6e750e
#define RGB_MAROON                      0x650021
#define RGB_BRIGHT_GREEN                0x01ff07
#define RGB_DARK_PURPLE                 0x35063e
#define RGB_MAUVE                       0xae7181
#define RGB_FOREST_GREEN                0x06470c
#define RGB_AQUA                        0x13eac9
#define RGB_CYAN                        0x00ffff
#define RGB_TAN                         0xd1b26f
#define RGB_DARK_BLUE                   0x00035b
#define RGB_LAVENDER                    0xc79fef
#define RGB_TURQUOISE                   0x06c2ac
#define RGB_DARK_GREEN                  0x033500
#define RGB_VIOLET                      0x9a0eea
#define RGB_LIGHT_PURPLE                0xbf77f6
#define RGB_LIME_GREEN                  0x89fe05
#define RGB_GREY                        0x929591
#define RGB_SKY_BLUE                    0x75bbfd
#define RGB_YELLOW                      0xffff14
#define RGB_MAGENTA                     0xc20078
#define RGB_LIGHT_GREEN                 0x96f97b
#define RGB_ORANGE                      0xf97306
#define RGB_TEAL                        0x029386
#define RGB_LIGHT_BLUE                  0x95d0fc
#define RGB_RED                         0xe50000
#define RGB_BROWN                       0x653700
#define RGB_PINK                        0xff81c0
#define RGB_BLUE                        0x0343df
#define RGB_GREEN                       0x15b01a
#define RGB_PURPLE                      0x7e1e9c
